details/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('friendlist/', views.friend_list, name="friendlist"),
    path('newfriends/', views.potential_friends, name="newfriends"),
    path('profilepage/<str:pk>/', views.profile_page, name="profilepage"),
    path('sendrequest/<str:pk>/', views.send_request, name="sendrequest"),
    path('friendrequest/', views.friend_request, name="friendrequest"),

]

posts/urls.py
from django.urls import path
from . import views

app_name='posts' #cuz we used namespace in project urls.py


urlpatterns = [
    path('create_post',views.create_post,name='create_post'),
    path('',views.post_view,name='post_list'),
    path('like/',views.like_post,name='like_post'),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('details.urls')),
    path('posts/',include('posts.urls', namespace='posts')),
]

details/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Profile(models.Model):

    Gender = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True, auto_now=True)
    gender = models.CharField(max_length=20, choices=Gender, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        if self.full_name == None:
            return "Full Name is NULL"
        return self.full_name

# class Friend(models.Model):
#     profile = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)


class FriendList(models.Model):
    profile1 = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    profile2 = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='profile2')
    is_friends = models.BooleanField(default=False)

    def __str__(self):
        return str('%s <-> %s' % (self.profile1.username, self.profile2.username))


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='sender')
    reciever = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='reciever')
    is_sent = models.BooleanField(default=False)

    def __str__(self):
        return str('%s -> %s' % (self.sender.username, self.reciever.username))

details/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *

class UserForm(UserCreationForm):
    Gender = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    full_name = forms.CharField(max_length=100)
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    email = forms.CharField(max_length=100, help_text='email')
    gender = forms.ChoiceField(choices=Gender)

    class Meta:
        model = User
        fields = ('username','password1','password2','email','full_name','birth_date','gender')

details/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from .models import *
from .forms import UserForm

# Create your views here.
@login_required(login_url='/login/')
def home(request):

    user = request.user

    context = {
        'user' : user,
    }

    return render(request, 'details/home_page.html', context)

def register_page(request):
    user_form = UserForm()
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db() 

            user.profile.full_name = user_form.cleaned_data.get('full_name')
            user.profile.birth_date = user_form.cleaned_data.get('birth_date')
            user.profile.email = user_form.cleaned_data.get('email')
            user.profile.gender = user_form.cleaned_data.get('gender')
            user.save()

            raw_password = user_form.cleaned_data.get('password1')
            username = user.username
            
            checked_user = authenticate(username=username, password=raw_password)
            login(request,checked_user)

            return redirect('home')

    context = {
        'user_form' : user_form,
    }

    return render(request, 'details/register_page.html', context)

def login_page(request):

    username = request.POST.get('username')
    password = request.POST.get('password')

    checked_user = authenticate(request, username=username, password = password)

    if request.user.is_authenticated:
        user=request.user
        return HttpResponse("Your'e alrady logged in. Goto 'https://sd17-social-live.herokuapp.com'")


    if checked_user is not None:
        login(request,checked_user)
        return redirect('home')
    else:
        messages.info(request,'Username or Password not correct')

    context={}
    return render(request, 'details/login_page.html', context)

@login_required(login_url='/login/')
def logout_page(request):
	logout(request)
	return redirect('login')

@login_required(login_url='/login/')
def friend_list(request):

    user = request.user
    friends_list = user.friendlist_set.all() | user.profile2.all()
    no_of_friends = user.friendlist_set.all().count() + user.profile2.all().count()
    context={
        'user':user,
        'friends':friends_list,
        'no_of_friends':no_of_friends
    }

    return render(request, 'details/friend_list.html', context)

@login_required(login_url='/login/')
def profile_page(request,pk):
    current_user = request.user
    view_user = User.objects.get(id=pk)
    is_sent = False
    is_received = False
    is_friends = False
    
    
    if(FriendList.objects.filter(profile1=current_user,profile2=view_user, is_friends = True).exists() | FriendList.objects.filter(profile1=view_user,profile2=current_user, is_friends = True).exists()):
        is_friends=True

    elif(FriendRequest.objects.filter(sender=current_user,reciever=view_user, is_sent=True).exists()):
        is_sent=True
    elif(FriendRequest.objects.filter(sender=view_user,reciever=current_user, is_sent=True).exists()):
        is_received = True
            

    print('view_user' , view_user,
        'current_user' , current_user,
        'is_sent' , is_sent,
        'is_friends' , is_friends)
 
    context={
        'view_user' : view_user,
        'current_user' : current_user,
        'is_sent' : is_sent,
        'is_friends' : is_friends,
        'is_received' : is_received,
    }

    return render(request, 'details/profile_page.html', context)

@login_required(login_url='/login/')
def send_request(request,pk):
    sender = request.user
    reciever = User.objects.get(id=pk)
    FriendRequest.objects.create(sender=sender,reciever=reciever, is_sent=True)
    return redirect('profilepage',pk=pk)

@login_required(login_url='/login/')
def potential_friends(request):
    current_user = request.user
    all_user = User.objects.filter().exclude(username=current_user)
    all_friends = current_user.friendlist_set.all() | current_user.profile2.all()
    new_friends = all_user
    for i in all_friends:
        new_friends = new_friends.exclude(pk=i.profile1.pk)
        new_friends = new_friends.exclude(pk=i.profile2.pk)
    no_of_friends = new_friends.count()

    context={
        'current_user' : current_user,
        'new_friends' : new_friends,
        'no_of_friends' : no_of_friends
    }
    return render(request, 'details/potential_friends.html',context)

@login_required(login_url='/login/')
def friend_request(request):
    current_user = request.user
    friend_request_recieved = FriendRequest.objects.filter(reciever=current_user,is_sent=True)

    if request.method == 'POST' and 'accept' in request.POST:
        
        sender=User.objects.get(id=int(request.POST.get('sender')))
        reciever=User.objects.get(id=int(request.POST.get('reciever')))
        FriendList.objects.create(profile1=sender, profile2=reciever, is_friends = True)
        FriendRequest.objects.get(sender=sender, reciever=reciever).delete()

    if request.method == 'POST' and 'reject' in request.POST:
        FriendRequest.objects.get(sender=sender, reciever=reciever).delete()

    context={
        'current_user' : current_user,
        'friend_request_recieved' : friend_request_recieved,
    }
    return render(request, 'details/friend_request.html',context)

details/templates/details/friend_list.html
{% extends 'details/main.html' %}


{% block content %}
    {% ifequal no_of_friends 0 %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/doodle.css' %}">
    
    <a class="btn btn-dark btn-lg" href="{% url 'newfriends' %}">Find New Friends Here</a>
    <h1 class="doodle">Sorry You don't have any friends</h1>
    
    {% else %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/blink.css' %}">
        <h1 class="blink">FriendList</h1>
        <div class="caveat"><h1>Your Total Friends :: {{no_of_friends}}</h1></div><br>
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Full Name</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Profile</th>
              </tr>
            </thead>
            <tbody>
                {% for i in friends %}
                    <tr>
                    {% ifequal  i.profile2.username user.username %}
                        <td class="caveat">{{i.profile1.profile.full_name}}</td>
                        <td class="caveat">{{i.profile1.username}}</td>
                        <td class="caveat">{{i.profile1.profile.email}}</td>
                        <td class="caveat"><a class='btn btn-secondary' href="{% url 'profilepage' i.profile1.id %}">Visit</a></td>

                    {% else %}
                        <td class="caveat">{{i.profile2.profile.full_name}}</td>
                        <td class="caveat">{{i.profile2.username}}</td>
                        <td class="caveat">{{i.profile2.profile.email}}</td>
                        <td class="caveat"><a class='btn btn-secondary'href="{% url 'profilepage' i.profile2.id %}">Visit</a></td>

                    {% endifequal %}
                
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endifequal %}
{% endblock %}

details/templates/details/friend_request.html
{% extends 'details/main.html' %}

{% block content %}
{% ifequal friend_request_recieved.count 0 %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/doodle.css' %}">
  <style>
    .doodle{
      font: normal 100px Varela Round, sans-serif;

    }
  </style>

    <h1 class="doodle">There's no new friend-requests for you </h1>
    {% else %}
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Full Name</th>
            <th scope="col">Username</th>
            <th scope="col">Accept</th>
            <th scope="col">Reject</th>
            <th scope="col">Profile</th>
          </tr>
        </thead>
        <tbody>
            {% for i in friend_request_recieved %}
          <tr>
            <td>{{i.sender.profile.full_name}}</td>
            <td>{{i.sender.username}}</td>
            <form method="POST">
            {% csrf_token %}
            <td><input type="submit" class="btn btn-warning" name="accept" value="accept"></td>
            <td><input type="submit" class="btn btn-danger" name="reject" value="reject"></td>
            <input type="hidden" name="sender" value={{i.sender.id}}>
            <input type="hidden" name="reciever" value={{i.reciever.id}}>   
            </form>
            <td><a class='btn btn-secondary'href="{% url 'profilepage' i.sender.id %}">Visit</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    
    
    
    {% endifequal %}
{% endblock %}

details/templates/details/home_page.html
{% extends 'details/main.html' %}
{% load static %}

{% block content %}

<style>
.parent{
grid-column-gap: 2px;
grid-row-gap: 2px; 
}



</style>
<link rel="stylesheet" type="text/css" href="{% static 'css/blink.css' %}">

    <h1 class="blink">Welcome, {{user.username}}</h1>
    
    <div class="parent">

        <div class="div1 item fatface" onclick="location.href='{% url 'posts:post_list' %}'"> 
            <h1>News Feed</h1>
        </div>

        <div class="div2 item fatface" onclick="location.href='{% url 'friendlist' %}'">
            <h1>Friends</h1>
        </div>

        <div class="div3 item fatface" onclick="location.href='{% url 'friendrequest' %}'">
            <h1> Requests</h1>
        </div>

        <div class="div4 item fatface" onclick="location.href='{% url 'posts:create_post' %}'">
            <h1> Write Your own Post</h1>
        </div>
        <div class="div5 item fatface" onclick="location.href='{% url 'newfriends' %}'">
            <h1>Find Friends</h1>
        </div>
    </div> 

{% endblock %}
    

details/templates/details/login_page.html
{% extends 'details/main.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>
<div class="wrapper fadeInDown">
    <div id="formContent">
          <!-- Tabs Titles -->
      <!-- Icon -->
    <div class="fadeIn first">
    <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="" />
    </div>
  
<form method="POST" action="">
    {% csrf_token %}
    <input type="text" class="fadeIn second" name="username" placeholder="Username..." >
    <input type="password" class="fadeIn third" name="password" placeholder="Password..."  >
    <input  class="fadeIn fourth"  type="submit" value="Login">
</form>
<div id="formFooter">

<div class="underlineHover" >
    Don't have an account?? <a href="{% url 'register' %}">Register Now !!</a>
</div>

</body>
</html>
{% endblock %}

details/templates/details/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social 1.0</title>
    
    <link type="text/css" rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Cinzel&family=Orbitron:wght@800&display=swap" rel="stylesheet"> 

</head>
<body>
    {% include 'details/navbar.html' %}

    {% block content %}



	{% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
</body>
</html>

details/templates/details/navbar.html
{% load static %}
<style>
    .hello-msg{
      font-size: 18px;
      color: #fff;
      margin-right: 20px;
    }
  </style>
  
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFFF63;">
    <a class="navbar-brand cinzel" href="{% url 'home' %}">Home</a>
    <!-- <img src="{% static 'images/logo.png' %}"> -->
    {% if request.user.is_authenticated %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav cinzel">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'profilepage' request.user.id %}">Profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'friendlist' %}">Friends</a>
          </li>          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'friendrequest' %}">Friend Request</a>
          </li>
          <li class="nav-item active">
           <a class="nav-link" href="{% url 'newfriends' %}">Find Friends</a>
         </li>
         <li class="nav-item active">
           <a class="nav-link" href="{% url 'posts:post_list' %}">See Posts</a>
         </li>
         <li class="nav-item active">
           <a class="nav-link" href="{% url 'posts:create_post' %}">Write Posts</a>
         </li>
      </ul>
    </div>
  
    <!-- <span class="hello-msg">Hello, {{request.user}}</span> -->
    <span ><a  class=" nav-link cinzel" href="{% url 'logout' %}">Logout</a></span>
    {%else%}
    {% endif %}
  
  </nav>
  

details/templates/details/potential_friends.html
{% extends 'details/main.html' %}

{% block content %}

    {% ifequal no_of_friends 0 %}
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/doodle.css' %}">

        <h1 class="doodle">Sorry, There's no new friends to suggest</h1>
    {% else %}
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Full Name</th>
            <th scope="col">Username</th>
            <th scope="col">Profile</th>
          </tr>
        </thead>
        <tbody>
          {% for i in new_friends %}
          <tr>
            <td>{{i.profile.full_name}}</td>
            <td>{{i.username}}</td>
            <td><a class='btn btn-secondary' href="{% url 'profilepage' i.id %}">Visit</a></td>
          </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endifequal %}

{% endblock %}

details/templates/details/profile_page.html
{% extends 'details/main.html' %}

{% block content %}
<style>
    .text{
        text-align:justify;
        padding-left: 7%;
        padding-top: 10%;
        padding-bottom: 10%;
        padding-right: 1%;
        cursor:default;
        height:500px;

    }
      .parent {
        display: grid;
        grid-template-columns: repeat(5, 1fr);
        grid-template-rows: 1fr;

        }
  
      .div1 { 
          grid-area: 1 / 2 / 2 / 5; 
    } 
  </style>

      
  {% load static %}
  <div class='orbitron'>
    Profile Page
  </div>




{% ifequal view_user.username current_user.username %}

{% else %}
    {% if is_friends %}
        <div class="caveat">alrady Friends</div>
    {% elif is_sent %}
        <div class="caveat">youv'e sent request alrady</div>
    {% elif is_received %}
        <div class="caveat">You've received request alrady</div> 
        <a class="caveat" href="{% url 'friendrequest' %}">Check here</a>
    {% else %}
        <a class="caveat" href="{% url 'sendrequest' view_user.id%}">seend-req</a>
    {% endif %}
{% endifequal %}
<div class="container ">
    <div class="divtra div5 text cinzel"><strong>
        Username : {{view_user.username}}<br>
        Fullname : {{view_user.profile.full_name}}<br>
        Gender : {{view_user.profile.gender}}<br>
        Email address : {{view_user.profile.email}}<br>
        Birth Date : {{view_user.profile.birth_date}}<br>
        Joined Since : {{view_user.profile.date_created}}<br>
      </strong>
    </div>
</div>

<!-- <a href="{% url 'newfriends' %}">Go back</a> -->

{% endblock %}

details/templates/details/register_page.html
{% extends 'details/main.html' %}

{% block content %}
<style>
  .text{
        text-align:justify;
        padding-left: 1%;
        padding-right: 1%;
        padding-bottom: 50px;
        width: auto;

    }
    .parent {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      grid-template-rows: 1fr;
      grid-column-gap: 0px;
      grid-row-gap: 0px;
      }

    .div1 { grid-area: 1 / 2 / 2 / 5; } 
</style>
<center><h1 class="orbitron">Registration Form</h1></center>
<div class="container parent ">
  <div class="divtra div1 text cinzel">
<form method="POST" class="sign-up-form">
    {% csrf_token %}
    {{ user_form.as_p }}
    <center>
      <button type="submit" class="btn btn-lg btn-dark">Submit</button>
      {{user_form.errors}}
      <div>alrady have an account <a href="{% url 'login' %}">Login Here</a></div>
    </center>
  </form>
</div>
</div>
{% endblock %}