posts/urls.py
from django.urls import path
from . import views

app_name='posts' #cuz we used namespace in project urls.py


urlpatterns = [
    path('create_post',views.create_post,name='create_post'),
    path('',views.post_view,name='post_list'),
    path('like/',views.like_post,name='like_post'),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('details.urls')),
    path('posts/',include('posts.urls', namespace='posts')),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=300, default='Title')
    body = models.TextField()
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')

    def __str__(self):
        return str(self.title)
    
    @property
    def num_likes(self):
        return self.liked.all().count()

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

    def __str__(self):
        return str(self.post)

posts/forms.py
from django.forms import ModelForm
from django import forms

from .models import *

class PostForm(ModelForm):
    class Meta:
        model = Post
        filter = '__all__'
        exclude = ['user']

posts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from .models import *


@login_required(login_url='/login/',redirect_field_name=None)
def create_post(request):
    user = request.user
    if request.method == 'POST':
        title = request.POST.get('title')
        body = request.POST.get('description')
        Post.objects.create(title=title, body=body, author=user)
    
    context = {}
    return render(request,'posts/create_post.html', context)

@login_required(login_url='/login/')
def post_view(request):
    # all_posts = Post.objects.all()
    user = request.user
    all_friends = user.friendlist_set.all() | user.profile2.all()
    # new_posts = None
    new_posts = ''
    for i in all_friends:
        new_posts = i.profile1.author.all() | i.profile2.author.all()
    # new_posts=Post.objects.all().first()

    # for i in all_friends:
    #     for j in i.profile1.author.all():
    #         new_posts = new_posts['post'].append(j)
    # for i in all_friends:
    #     for j in i.profile2.author.all():
    #         new_posts = new_posts['post'].append(j)


    print('other',new_posts)
    try:
        new_posts = new_posts | user.author.all()
    except:
        new_posts=user.author.all()
    print('my',new_posts)


    context = {
        'all_posts' : new_posts,
        'user' : user
    }

    return render(request, 'posts/posts_list.html', context)

@login_required(login_url='/login/')
def like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('id')  
        post_obj = Post.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = Like.objects.get_or_create(user=user, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect('posts:post_list')

posts/templates/posts/create_post.html
{% extends 'details/main.html' %}

{% block content %}
{% load static %}
<style>
    
    .text{
        text-align:center;
        padding-left: 1%;
        
        padding-right: 1%;
        
    }
    
    
</style>
    <link rel="stylesheet" type="text/css" href="{% static 'css/glitch.css' %}">
    <br>
<div class="text_container">
    <h1 class="glitch">Write a post :</h1>
    <h1 class="glitch">Write a post :</h1>
    <h1 class="glitch">Write a post :</h1>
</div>
<div class="container ">
    <div class="divtra div5 text ">
<form action="" method="POST">{% csrf_token %}
    <label for="title" class='form-group'><h3 class="cinzel">Title:</h3></label><br>
    <input class='form-control'type="text" id="title" name="title" required><br>
    <label class="form-group"for="description"><h3 class="cinzel">Description:</h3></label><br>
    <input class="form-control form-control-lg"type="text" id="description" name="description" required><br>
    <button class="btn btn-warning btn-lg btn-block" type ='submit'>Submit</button>
</form>
</div>
</div>

{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'details/main.html' %}

{% block content %}
<style>
        
    .text{
        text-align:justify;
        padding-left: 1%;
        padding-top: 5%;
        padding-bottom: 1%;
        padding-right: 1%;
        cursor:default;

    }

.h4{
  background-color: white;
  color: white;
}

</style>
    {% if all_posts.count %}
        {% for i in all_posts %}
        <div class="container ">
            <div class="divtra div5 text caveat">
                
                <h3>{{i.title}}</h3><br>
                {{i.body}}<br>
                <p>Posted by, <a href="{% url 'profilepage' i.id %}">{{i.author.username}}</a><br>
                <form action="{% url 'posts:like_post' %}" method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name='id' value="{{i.id}}">
                    {% if user not in i.liked.all %}
                        <button class='btn btn-outline-primary' type ='submit'>Like</button>
                    {% else %}
                        <button class='btn btn-outline-secondary' type ='submit'>Unlike</button>
                    {% endif %}
                    <strong>{{i.liked.all.count}} Likes</strong><br>
                </form>
                </p>
            </div>
            
        </div>
        {% endfor %}
    {% else %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/doodle.css' %}">

        <a class="btn btn-dark btn-lg" href="{% url 'posts:create_post' %}">Write a post</a>
            <h1 class="doodle">Sorry, No post to see</h1>
    {% endif %}
{% endblock %}